### ISSUE TITLE
how can I use this code for predicting flight ticket price?

### ISSUE THREAD

**Issue by mrmrn** [ArushiJindal/VehiclePricePrediction#1]
hi
thank you for the repo.
I have 2 weeks of data about some airlines ticket prices.the data contains hourly snapshot of ticket prices.
each snapshot contains flight number,departure date, flight price at the snapshot time, and..
could I use this code for predicting flight price and how?

**Comment by ArushiJindal** [comment]
This code as is will not be able to adapt for your problem. Best thing that comes to my mind to deal with Flight prices prediction is to look into Time Series Algorithms

**Comment by mrmrn** [comment]
thank you!
